name: deploy to remote

on:
  push:
    branches:
      - master
jobs:
  job1:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: ssh and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ./arisumi-design.com/public_html/wp-content/themes/Portfolio/local.a-design.com
            git checkout master
            git pull origin master
