name: Release to Develop Environment
on:
  push:
    branches:
      - develop

jobs:
  job1:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: ssh and deploy
        uses: appleboy/ssh-action@wordpress
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /arisumi-design.com/public_html/wp-content/themes/Portfolio/
            git checkout develop
            git pull origin develop