# This is a basic workflow that is manually triggered

name: Release to Develop Environment

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches:
      - developer

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job1:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: ssh and deploy
        uses: appleboy/ssh-action@Wordpress
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /arisumi-design.com/public_html/wp-content/themes/Portfolio/.git
            git checkout develop
            git pull origin developer
